routes/web.php
<?php

use App\Http\Controllers\DemandControler;
use App\Http\Controllers\DemandTreatmentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Mailcontroller;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $name = Route::currentRouteName();
    return view('front-office.welcome', [
        'name' => $name,
        'success' => false,
    ]);
})->name('home');

Route::get('/seach-demand', [DemandControler::class, 'SearchDemandView'])->name('demand.search');
Route::post('/seach-demand', [DemandControler::class, 'searchDemand'])->name('search.submit');
Route::post('/save-demand', [DemandControler::class, 'save'])->name('demand.save');
Route::get('/demand-code', [DemandControler::class, 'demandCodeView'])->name('demand.code');
Route::get('/result', [DemandControler::class, 'demandCodeView'])->name('search.result');
Route::get('/new-demand', [DemandControler::class, 'newDemandView'])->name('demand.new');

Route::post('/new-mail', [MailController::class, 'send'])->name('new.email');


 //backoffice routes
 //Authentification
 Route::get('login', [AuthController::class, 'index'])->name('login');
 Route::post('post-login', [AuthController::class, 'postLogin'])->name('login.post'); 
 Route::post('post-registration', [AuthController::class, 'postRegistration'])->name('register.post'); 
 Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    //admin
    Route::get('/index', [AuthController::class, 'index_backoffice'])->name('/index');
    Route::get('/awaiting-list', function () { return view('back-office.awaiting-list');})->name('/awaiting-list');
    Route::get('/awaiting-demand-list', [DemandTreatmentController::class, 'awaiting_demand'])->name('awaiting-demand-list');

    Route::get('/treated-list', function () { return view('back-office.treated-list');})->name('/treated-list');
    Route::get('/treated-demand-list', [DemandTreatmentController::class, 'treated_demand'])->name('treated-demand-list');

    Route::get('/rejected-list', function () { return view('back-office.rejected-list');})->name('/rejected-list');
    Route::get('/rejected-demand-list', [DemandTreatmentController::class, 'rejected_demand'])->name('rejected-demand-list');

    Route::get('/agent-demand-treated', [DemandTreatmentController::class, 'agent_demand_treated'])->name('agent-demand-treated');
    Route::get('/all-demand-treated', [DemandTreatmentController::class, 'all_demand_treated'])->name('all-demand-treated');

    Route::get('/agent-point', function () { return view('back-office.agent-point');})->name('/agent-point');
    Route::get('/agent-points', [DemandTreatmentController::class, 'pointByAgent'])->name('/agent-points');
    Route::get('/search', [DemandTreatmentController::class, 'search'])->name('search');

    //Agent
    Route::get('/treatment', [DemandTreatmentController::class, 'treatment'])->name('/treatment');
    Route::post('saveTreatment', [DemandTreatmentController::class, 'save_treatment'])->name('saveTreatment');
    Route::get('/agent-treated-list', function () { return view('back-office.agent-treated-list');})->name('/agent-treated-list');
    Route::get('/customers-message', function () { return view('back-office.customers-message');})->name('/customers-message');
    Route::get('/agent-treatment', [DemandTreatmentController::class, 'agent_treatment'])->name('agent-treatment');


    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
   
    Route::get('/mail-list', [Mailcontroller::class, 'getMailList'])->name('/mail-list');
});

resources/views/back-office/agent-point.blade.php
@extends('layouts.app-backoffice')
@section('content')
    <div class="container-fluid">

        <div class="col-md-12 col-xs-12">
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="date_debut" style="font-weight:bold">De :</label>
                    <input id="date_debut" name="date_debut" placeholder="Date_debut" class="form-control" type="date"
                        autocomplete="off" required="" value="<?php echo !empty($_POST['date_debut']) ? trim($_POST['date_debut']) : ''; ?>">
                </div>

                <div class="form-group col-md-4">
                    <label for="date_fin" style="font-weight:bold">à :</label>
                    <input id="date_fin" name="date_fin" placeholder="Date_fin" class="form-control" type="date"
                        autocomplete="off" required="" value="<?php echo !empty($_POST['date_fin']) ? trim($_POST['date_fin']) : ''; ?>">
                </div>

                <div class="form-group col-md-4">
                    <label for="agent" style="font-weight:bold">Agent :</label>
                    <select name="agent" class="form-control" id="agent" required>
                        <option value="TOUT">TOUT</option>
                    </select>
                </div>

                <div class="form-group col-md-4">
                    <button style="font-weight: bold;" type="button" class="btn btn-primary" id="search-button"
                        name="rechercher">Rechercher</button>
                </div>
            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Point par agent</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nom de l'agent</th>
                                <th>Total des demandes traitées</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>



    <script>
        var date_debut = document.getElementById('date_debut');
        var date_fin = document.getElementById('date_fin');
        var agent = document.getElementById('agent');
        if (date_debut != null) {
            date_debut.max = new Date().toISOString().split("T")[0];
        }
        if (date_fin != null) {
            date_fin.max = new Date().toISOString().split("T")[0];
        }

        $(document).ready(function() {
            $("#search-button").click(function() {
                var start_date = $("#date_debut").val();
                var end_date = $("#date_fin").val();
                var agent = $("#agent").val();
                $.ajax({
                    type: 'GET',
                    url: '{{ route('search') }}',
                    data: {
                        "_token": "{{ csrf_token() }}",
                        "start_date": start_date,
                        "end_date": end_date,
                        "agent": agent
                    },
                    success: function(data) {
                        $("#dataTable").DataTable()
                        var table = $('#dataTable').DataTable();
                        table.clear();
                        table.rows.add(data).draw();
                    }
                });
            });
        });


        $(document).ready(function() {

            $('#dataTable').DataTable({
                responsive: true,
                orderCellsTop: true,
                fixedHeader: true,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
                },
                "order": [
                    [0, 'desc']
                ],
                "ajax": {
                    url: "{{ url('/agent-points') }}",
                    dataType: 'JSON',
                },

                "columns": [{
                        "data": "name"
                    },
                    {
                        "data": "total"
                    },
                ],
                "columnDefs": [{
                    render: function(data, type, row, meta) {
                        if (data === null) {
                            return "Pas de Resultats";
                        } else {
                            return data;
                        }
                    }
                }, ],

            });

        });
    </script>
@endsection

resources/views/back-office/agent-treated-list.blade.php
@extends('layouts.app-backoffice')
@section('content')
<div class="container-fluid">

                
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Mes Demandes MAJ Traitées</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>Numéro</th>
                                            <th>Code</th>
                                            <th>Traitement</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

                

<script>

 $(document).ready(function(){

    $('#dataTable').DataTable({
        responsive: true,
        orderCellsTop: true,
        fixedHeader: true,
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
        },
        "order": [[0, 'desc']],
        "ajax" : {
            url:"{{url('/agent-treatment')}}",
            dataType:'JSON'
        },
      
        "columns":[
            { "data": "treatment_at" },
            { "data": "number_to_change" },
            { "data": "code" },
            { "data": "treatment" },
            { "data": "status" }
        ],
        "columnDefs":[
            {
               render : function(data, type, row, meta){
                 if (data===null){
                   return "Pas de Resultats";
                  } else {
                    return data;
                  }
              }
            },
        ],

    });

 });

</script>

               
@endsection

resources/views/back-office/awaiting-list.blade.php
@extends('layouts.app-backoffice')
@section('content')

                <div class="container-fluid">
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Demandes en attente</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>Numéro</th>
                                            <th>Code</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

                
<script>

 $(document).ready(function(){

    $('#dataTable').DataTable({
        responsive: true,
        orderCellsTop: true,
        fixedHeader: true,
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
        },
        "order": [[0, 'desc']],
        "ajax" : {
            url:"{{url('/awaiting-demand-list')}}",
            dataType:'JSON'
        },
      
        "columns":[
            { "data": "created_at" },
            { "data": "number_to_change" },
            { "data": "code" },
            { "data": "status" }
        ],
        "columnDefs":[
            {
               render : function(data, type, row, meta){
                 if (data===null){
                   return "Pas de Resultats";
                  } else {
                    return data;
                  }
              }
            },

        ],

    });

 });

</script>

               
@endsection

resources/views/back-office/create-user.blade.php
@extends('layouts.app-backoffice')
@section('content')
<div class="container-fluid">
                    <div class="col-md-12 col-xs-12">
                        
                    </div>
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <div class="col-mb-2">
                                <a class="btn btn-primary" href="{{ route('users.index') }}"> Les utilisateurs</a>
                            </div>
                        </div>
                        
                        <div class="card-body">

                                @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                    </ul>
                                </div>
                                @endif


                                 <form action="{{ route('users.store') }}" method="POST" class="user">
                                     
                                        @csrf
                                        
                                        <div class="row">
                                            <div class="col-md-6">
                                                <input type="text" class="form-control" name="name" placeholder="Nom Complet" required>
                                            </div>
                                            <div class="col-md-6">
                                                <input type="email" class="form-control" name="email" placeholder="Email" required>
                                            </div>
                                        </div>

                                        <div class="row mt-3">
                                            <div class="col-md-6">
                                                <input type="password" class="form-control" name="password" placeholder="Mot de passe" required>
                                            </div>
                                            <div class="col-md-6">
                                                <input type="password" class="form-control" name="confirm-password" placeholder="Confirmer Mot de passe" required>
                                            </div>
                                        </div>

                                        <div class="form-group mt-3">
                                            <strong>Role:</strong>
                                            {!! Form::select('roles[]', $roles,[], array('class' => 'form-control','multiple')) !!}
                                        </div>
                                
                                        <button class="btn btn-primary mt-3">
                                            Enregistrer
                                        </button>

                                 </form>
                            
                        </div>
                    </div>

                </div>

                

<script>
       
        var date_debut = document.getElementById('date_debut');
        var date_fin = document.getElementById('date_fin');

        if (date_debut != null) {
            date_debut.max = new Date().toISOString().split("T")[0];
        }
        if (date_fin != null) {
            date_fin.max = new Date().toISOString().split("T")[0];
        }

 </script>
               
@endsection

resources/views/back-office/customers-message.blade.php
@extends('layouts.app-backoffice')
@section('content')
    <div class="container-fluid">


        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Mes Demandes MAJ Traitées</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nom de l'abonné</th>
                                <th>Email</th>
                                <th>Raison</th>
                                <th>Message</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>



    <script>
        $(document).ready(function() {

            $('#dataTable').DataTable({
                responsive: true,
                orderCellsTop: true,
                fixedHeader: true,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
                },
                "order": [
                    [0, 'desc']
                ],
                "ajax": {
                    url: "{{ url('/mail-list') }}",
                    dataType: 'JSON'
                },

                "columns": [{
                        "data": "name"
                    },
                    {
                        "data": "email"
                    },
                    {
                        "data": "raison"
                    },
                    {
                        "data": "message"
                    },
                ],
                "columnDefs": [{
                    render: function(data, type, row, meta) {
                        if (data === null) {
                            return "Pas de Resultats";
                        } else {
                            return data;
                        }
                    }
                }, ],

            });

        });
    </script>
@endsection

resources/views/back-office/edit-user.blade.php
@extends('layouts.app-backoffice')
@section('content')
<div class="container-fluid">
                   
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <div class="col-mb-2">
                                <a class="btn btn-primary" href="{{ route('users.index') }}"> Les utilisateurs </a>
                            </div>
                        </div>
                        
                        <div class="card-body">

                                @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                    </ul>
                                </div>
                                @endif

                                    {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id]]) !!}
                                    
                                        @csrf
                                        
                                        <div class="row">
                                            <div class="col-md-6">
                                            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                                            </div>
                                            <div class="col-md-6">
                                            {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}                                            </div>
                                        </div>

                                        <div class="row mt-3">
                                            <div class="col-md-6">
                                            {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}                                            </div>
                                            <div class="col-md-6">
                                            {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}                                            </div>
                                        </div>

                                        <div class="form-group mt-3">
                                        <strong>Rôle:</strong>
                                            {!! Form::select('roles[]', $roles,$userRole, array('class' => 'form-control','multiple')) !!}
                                        </div>

                                        <button class="btn btn-primary mt-3">
                                            Enregistrer
                                        </button>

                                    {!! Form::close() !!}

                        </div>
                        
                    </div>

                </div>

                

<script>
       
        var date_debut = document.getElementById('date_debut');
        var date_fin = document.getElementById('date_fin');

        if (date_debut != null) {
            date_debut.max = new Date().toISOString().split("T")[0];
        }
        if (date_fin != null) {
            date_fin.max = new Date().toISOString().split("T")[0];
        }

 </script>
               
@endsection

resources/views/back-office/show-user.blade.php
@extends('layouts.app-backoffice')
@section('content')
<div class="container-fluid">
                   
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <div class="col-mb-2">
                                <a class="btn btn-primary" href="{{ route('users.index') }}"> Les utilisateurs </a>
                            </div>
                        </div>
                        
                        <div class="card-body">
                           <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Nom:</strong>
                                        {{ $user->name }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Email:</strong>
                                        {{ $user->email }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Rôles:</strong>
                                        @if(!empty($user->getRoleNames()))
                                            @foreach($user->getRoleNames() as $v)
                                                <label class="badge badge-success">{{ $v }}</label>
                                            @endforeach
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>

                </div>

                

<script>
       
        var date_debut = document.getElementById('date_debut');
        var date_fin = document.getElementById('date_fin');

        if (date_debut != null) {
            date_debut.max = new Date().toISOString().split("T")[0];
        }
        if (date_fin != null) {
            date_fin.max = new Date().toISOString().split("T")[0];
        }

 </script>
               
@endsection

resources/views/back-office/users.blade.php
@extends('layouts.app-backoffice')
@section('content')
<div class="container-fluid">
                    <div class="col-md-12 col-xs-12">
                        <h6 class="m-0 font-weight-bold text-primary">Gestion Utilisateur</h6>
                    </div>
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <div class="col-mb-2">
                                <a class="btn btn-primary" href="{{ route('users.create') }}"> Ajouter un utilisateur</a>
                            </div>
                        </div>
                        
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>N</th>
                                            <th>Nom</th>
                                            <th>Email</th>
                                            <th>Rôles</th>
                                            <th width="280px">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($data as $key => $user)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>
                                                @if(!empty($user->getRoleNames()))
                                                    @foreach($user->getRoleNames() as $v)
                                                    <label class="badge badge-success">{{ $v }}</label>
                                                    @endforeach
                                                @endif
                                            </td>
                                            <td>
                                            <a class="btn btn-info" href="{{ route('users.show',$user->id) }}">Voir</a>
                                            <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">Modifier</a>
                                                {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
                                                    {!! Form::submit('Supprimer', ['class' => 'btn btn-danger']) !!}
                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

                

<script>
       
        var date_debut = document.getElementById('date_debut');
        var date_fin = document.getElementById('date_fin');

        if (date_debut != null) {
            date_debut.max = new Date().toISOString().split("T")[0];
        }
        if (date_fin != null) {
            date_fin.max = new Date().toISOString().split("T")[0];
        }

 </script>
               
@endsection