routes/web.php
<?php

use App\Http\Controllers\DemandControler;
use App\Http\Controllers\DemandTreatmentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Mailcontroller;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $name = Route::currentRouteName();
    return view('front-office.welcome', [
        'name' => $name,
        'success' => false,
    ]);
})->name('home');

Route::get('/seach-demand', [DemandControler::class, 'SearchDemandView'])->name('demand.search');
Route::post('/seach-demand', [DemandControler::class, 'searchDemand'])->name('search.submit');
Route::post('/save-demand', [DemandControler::class, 'save'])->name('demand.save');
Route::get('/demand-code', [DemandControler::class, 'demandCodeView'])->name('demand.code');
Route::get('/result', [DemandControler::class, 'demandCodeView'])->name('search.result');
Route::get('/new-demand', [DemandControler::class, 'newDemandView'])->name('demand.new');

Route::post('/new-mail', [MailController::class, 'send'])->name('new.email');


 //backoffice routes
 //Authentification
 Route::get('login', [AuthController::class, 'index'])->name('login');
 Route::post('post-login', [AuthController::class, 'postLogin'])->name('login.post'); 
 Route::post('post-registration', [AuthController::class, 'postRegistration'])->name('register.post'); 
 Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    //admin
    Route::get('/index', [AuthController::class, 'index_backoffice'])->name('/index');
    Route::get('/awaiting-list', function () { return view('back-office.awaiting-list');})->name('/awaiting-list');
    Route::get('/awaiting-demand-list', [DemandTreatmentController::class, 'awaiting_demand'])->name('awaiting-demand-list');

    Route::get('/treated-list', function () { return view('back-office.treated-list');})->name('/treated-list');
    Route::get('/treated-demand-list', [DemandTreatmentController::class, 'treated_demand'])->name('treated-demand-list');

    Route::get('/rejected-list', function () { return view('back-office.rejected-list');})->name('/rejected-list');
    Route::get('/rejected-demand-list', [DemandTreatmentController::class, 'rejected_demand'])->name('rejected-demand-list');

    Route::get('/agent-demand-treated', [DemandTreatmentController::class, 'agent_demand_treated'])->name('agent-demand-treated');
    Route::get('/all-demand-treated', [DemandTreatmentController::class, 'all_demand_treated'])->name('all-demand-treated');

    Route::get('/agent-point', function () { return view('back-office.agent-point');})->name('/agent-point');
    Route::get('/agent-points', [DemandTreatmentController::class, 'pointByAgent'])->name('/agent-points');
    Route::get('/search', [DemandTreatmentController::class, 'search'])->name('search');

    //Agent
    Route::get('/treatment', [DemandTreatmentController::class, 'treatment'])->name('/treatment');
    Route::post('saveTreatment', [DemandTreatmentController::class, 'save_treatment'])->name('saveTreatment');
    Route::get('/agent-treated-list', function () { return view('back-office.agent-treated-list');})->name('/agent-treated-list');
    Route::get('/customers-message', function () { return view('back-office.customers-message');})->name('/customers-message');
    Route::get('/agent-treatment', [DemandTreatmentController::class, 'agent_treatment'])->name('agent-treatment');


    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
   
    Route::get('/mail-list', [Mailcontroller::class, 'getMailList'])->name('/mail-list');
});

resources/views/layouts/partials/footer-backoffice.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Webcoom 2023</span>
        </div>
    </div>
</footer>

resources/views/layouts/partials/footer.blade.php
<div class="container-fluid p-0">
    <footer class="text-center text-lg-start" style="background-color: #005aa4e7;">
        <div class="container d-flex justify-content-center py-5 mx-auto">
            <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #005aa4e7 !important; border-color:#fff">
                <a target="_blank" href="https://www.facebook.com/moovafricabeninofficiel" class="text-light"><svg
                        xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-facebook" viewBox="0 0 16 16">
                        <path
                            d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                    </svg></a>
            </button>
            <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #005aa4e7 !important; border-color:#fff">
                <a href="https://www.youtube.com/@moovafricabenin7248" target="_blank" rel="noopener noreferrer"
                    class="text-light"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                        fill="currentColor" class="bi bi-youtube" viewBox="0 0 16 16">
                        <path
                            d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z" />
                    </svg></a>

            </button>
            <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #005aa4e7 !important; border-color:#fff">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                        fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                        <path
                            d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
                    </svg>
            </button>
            <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #005aa4e7 !important; border-color:#fff">
                <a href="https://twitter.com/MoovAfricaBenin" target="_blank" rel="noopener noreferrer" class="text-light"><svg
                        xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-twitter" viewBox="0 0 16 16">
                        <path
                            d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
                    </svg></a>
            </button>
        </div>
        <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © {{ date('Y') }} Copyright:
            <a class="text-white" style="text-decoration: none" href="https://moov-africa.bj/">Moov.bj</a>
        </div>
    </footer>
</div>

resources/views/layouts/partials/header-back.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
</button>


<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">


    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{Auth::user()->name}}</span>
            <img class="img-profile rounded-circle" src="https://esim-front.webcoom.net/assets/img/logo-moov.png" alt="" title=""
                    style="width: 100px" />
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="userDropdown">
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ route('logout') }}">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Se déconnecter
            </a>
        </div>
    </li>

</ul>

</nav>

resources/views/layouts/partials/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top p-3 text-dark"
    style="box-shadow: 0px 5px 5px rgb(189 189 189 / 34%);">
    <div class="container-fluid col-lg-10 col-md-12 col-sm-12">
        <div id="logo">
            <a href="/"><img src="{{ asset('front-office/favicon.png') }}" alt=""
                    title="" style="width: 100px" /></a>
        </div>
        <button style="background-color: #fff !important" class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item text-center">
                    <a href="/"
                        class="nav-link m-2 active @if ($name === 'home') is-active @endif">Accueil
                    </a>
                </li>
                <li class="nav-item text-center">
                    <a href="/new-demand"
                        class="nav-link m-2 active @if ($name === 'demand.new') is-active @endif">Nouvelle
                        demande</a>
                </li>
                <li class="nav-item text-center">
                    <a href="/seach-demand"
                        class="nav-link m-2  active @if ($name === 'demand.search') is-active @endif">Rechercher
                        demande</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/partials/nav-backoffice.blade.php
 <!-- Sidebar -->
 <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

     <!-- Sidebar - Brand -->
     <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
         <div class="sidebar-brand-icon rotate-n-15">
             <img src="https://esim-front.webcoom.net/assets/img/logo-moov.png" alt="" title=""
                 style="width: 100px" />
         </div>
         <div class="sidebar-brand-text mx-3">Backoffice MAJ <sup>E-SIM</sup></div>
     </a>

@can('demand-treatment')
<!-- Divider -->
<hr class="sidebar-divider">
<!-- Divider -->
<div class="sidebar-heading">
 Agent 
</div>
<!-- Heading -->
<!-- Nav Item - Charts -->
<li class="nav-item">
    <a class="nav-link" href="/treatment">
        <i class="fas fa-fw fa-table"></i>
        <span> Traiter une demande</span></a>
</li>
@endcan

@can('agent-treatment-list')
<li class="nav-item">
    <a class="nav-link" href="/agent-treated-list">
        <i class="fas fa-fw fa-table"></i>
        <span> Mes Demandes Traitées</span></a>
</li>
@endcan

<li class="nav-item">
        <a class="nav-link" href="/customers-message">
        <i class="fas fa-fw fa-table"></i>
        <span>Messages des abonnés</span></a>
</li>

@if (Auth::user()->hasRole('Admin'))
        <hr class="sidebar-divider d-none d-md-block">
        <div class="sidebar-heading">
        Admin 
        </div>
@endif

@can('demands-list')
        <!-- Nav Item - Tables -->
        <li class="nav-item">
            <a class="nav-link" href="/awaiting-list">
                <i class="fas fa-fw fa-table"></i>
                <span>En attente de traitement</span></a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/treated-list">
                <i class="fas fa-fw fa-table"></i>
                <span>Traitées</span></a>
        </li>
@endcan

@can('agent-point')
        <hr class="sidebar-divider d-none d-md-block">
        <!-- Heading -->
        <div class="sidebar-heading">
        Points
        </div>

        <li class="nav-item">
            <a class="nav-link" href="/agent-point">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Point par agent</span></a>
        </li>
@endcan

@can('add-user')
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fas fa-fw fa-wrench"></i>
                <span>Paramètres Utilisateur</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" href="{{ route('users.index') }}">Gestion Utilisateur</a>
                    @if (Auth::user()->hasRole('Admin'))
                    <a class="collapse-item" href="{{ route('roles.index') }}">Gestion Rôle</a>
                    @endif
                </div>
            </div>
        </li>
@endcan

<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">



     <!-- Sidebar Toggler (Sidebar) -->
     <div class="text-center d-none d-md-inline">
         <button class="rounded-circle border-0" id="sidebarToggle"></button>
     </div>


 </ul>
 <!-- End of Sidebar -->